# Default colors
[colors.primary]
background = '0x220434'
foreground = '0xc39fd5'

[colors.normal]
black = "#262335"
red = "#fe4450"
green = "#72f1b8"
yellow = "#f3e70f"
blue = "#03edf9"
magenta = "#ff7edb"
cyan = "#03edf9"
white = "#ffffff"

[colors.bright]
black = "#614d85"
red = "#fe4450"
green = "#72f1b8"
yellow = "#fede5d"
blue = "#03edf9"
magenta = "#ff7edb"
cyan = "#03edf9"
white = "#ffffff"

[window]
opacity = 0.85
# below line is used for removing the bar
#deco

[window.dimensions]
columns = 150
lines = 50

[terminal.shell]
program = "tmux"

[env]
TERM = "tmux-256color"
